### ISSUE TITLE
[Suggestion] Visible Tag Button

### ISSUE THREAD

**Issue by Stanzilla** [jldiaz/mkdocs-plugin-tags#4]
Heya, I picked up your cool plugin for my docs and made a tag button for each page, since you seemed to be interested in doing that as well, here's my code as inspiration:

base.html

```jinja
<!-- Tags-->
{% if not (page.is_homepage or page.meta.hide_tags) %}
	{% for tag in page.meta.tags %}
		<a href="{{ '/tags/' | url }}#{{ tag }}" title="{{ tag }}" class="md-tag">
			{% include ".icons/material/tag.svg" %}
			{{ tag }}
		</a>
	{% endfor %}
{% endif %}
```

```scss
// Tag
.md-tag {
  display: inline-block;
  margin: px2rem(9px) 0;
  padding-right: px2rem(10px);
  border-radius: px2rem(4px);
  background-color: lighten($manticore-black, 5%);
  font-size: ms(-1);
  list-style-type: none;
  cursor: pointer;
  overflow: hidden;
  color: $md-color-white !important;

  // Icon
  svg {
    display: inline-block;
    margin-right: px2rem(5px);
    padding: px2rem(2px) px2rem(8px);
    width: 38px;
    height: 38px;
    background-color: lighten($manticore-black, 15%);
    vertical-align: middle;
    fill: $md-color-white--light;
  }

  // Hovered tag
  &:hover {
    @include z-depth-focus;
    // background-color: lighten($manticore-black, 15%);

    // Icon
    svg {
      fill: var(--color-accent);
      background-color: lighten($manticore-black, 5%);
    }
  }
}
```
